export const GET_GRAPH_DATA = 'GET_GRAPH_DATA';
export const GET_GRAPH_DATA_LOADING = 'GET_GRAPH_DATA_LOADING';

export const GET_TXS_GRAPH_DATA = 'GET_TXS_GRAPH_DATA';
export const GET_TXS_GRAPH_DATA_LOADING = 'GET_TXS_GRAPH_DATA_LOADING';

export const GET_COIN_MARKET_CAP_DATA = 'GET_COIN_MARKET_CAP_DATA';
export const GET_COIN_MARKET_CAP_DATA_LOADING =
  'GET_COIN_MARKET_CAP_DATA_LOADING';
