export const GET_BLOCKS_INFO = 'GET_BLOCKS_INFO';
export const GET_BLOCKS_INFO_LOADING = 'GET_BLOCKS_INFO_LOADING';

export const GET_ALL_BLOCKS = 'GET_ALL_BLOCKS';
export const GET_ALL_BLOCKS_LOADING = 'GET_ALL_BLOCKS_LOADING';

export const GET_BLOCKS_BY_HEIGHT = 'GET_BLOCKS_BY_HEIGHT';
export const GET_BLOCKS_BY_HEIGHT_LOADING = 'GET_BLOCKS_BY_HEIGHT_LOADING';

export const GET_LATEST_BLOCKS = 'GET_LATEST_BLOCKS';
export const GET_LATEST_BLOCKS_LOADING = 'GET_LATEST_BLOCKS_LOADING';

export const GET_TRANSACTIONS_BY_BLOCK_HEIGHT =
  'GET_TRANSACTIONS_BY_BLOCK_HEIGHT';
export const GET_TRANSACTIONS_BY_BLOCK_HEIGHT_LOADING =
  'GET_TRANSACTIONS_BY_BLOCK_HEIGHT_LOADING';
